<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>AelfeyjaRescue</AssemblyName>
    <RootNamespace>AelfeyjaRescue</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Bannerlord.ReferenceAssemblies.Core" Version="1.4.0.112726-beta" PrivateAssets="All" />
    <PackageReference Include="Lib.Harmony" Version="2.3.6" PrivateAssets="All" />
  </ItemGroup>
</Project>
